#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# MaNGOS is a full featured server for World of Warcraft, supporting
# the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
#
# Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Generate the custody-pinned Classic 5875 Warden module C++ resource."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


EXPECTED_LENGTH = 18_756
EXPECTED_MD5 = "79c0768d657977d697e10bad956cced1"
EXPECTED_SHA256 = "6c68006a2f1fd31e7208204b3f7ceb94a6ce977876e13f2f703e9cd644482289"


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_header() -> str:
    return """/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Generated by extra/warden/generate_warden_module_resource.py.
 */

#ifndef MANGOS_WARDEN_MODULE_WIN_5875_DATA_H
#define MANGOS_WARDEN_MODULE_WIN_5875_DATA_H

#include \"Platform/Define.h\"

#include <cstddef>

namespace warden
{
extern uint8 const WardenModuleWin5875Data[18756];
extern size_t const WardenModuleWin5875Size;
}

#endif
"""


def generate_source(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16])
        rows.append(f"    {row},")

    return """/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Generated by extra/warden/generate_warden_module_resource.py from the
 * custody-pinned encrypted signed module. Do not edit by hand.
 */

#include \"WardenModuleWin5875Data.h\"

namespace warden
{
uint8 const WardenModuleWin5875Data[18756] =
{
""" + "\n".join(rows) + """
};

size_t const WardenModuleWin5875Size = sizeof(WardenModuleWin5875Data);
}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    args = parser.parse_args()

    data = args.input.read_bytes()
    if len(data) != EXPECTED_LENGTH:
        raise SystemExit(f"module length {len(data)} != {EXPECTED_LENGTH}")
    if hashlib.md5(data).hexdigest() != EXPECTED_MD5:
        raise SystemExit("module MD5 does not match the custody manifest")
    if hashlib.sha256(data).hexdigest() != EXPECTED_SHA256:
        raise SystemExit("module SHA-256 does not match the custody manifest")

    write_if_changed(args.header, generate_header())
    write_if_changed(args.source, generate_source(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
