/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Generated by extra/warden/generate_warden_module_resource.py.
 */

#ifndef MANGOS_WARDEN_MODULE_WIN_5875_DATA_H
#define MANGOS_WARDEN_MODULE_WIN_5875_DATA_H

#include "Platform/Define.h"

#include <cstddef>

namespace warden
{
extern uint8 const WardenModuleWin5875Data[18756];
extern size_t const WardenModuleWin5875Size;
}

#endif
