# Download URL -> OUT if OUT does not already exist. Used from POST_BUILD.
if(NOT DEFINED URL OR NOT DEFINED OUT)
    message(FATAL_ERROR "DownloadIfMissing.cmake needs -DURL= and -DOUT=")
endif()
if(EXISTS "${OUT}")
    return()
endif()
message(STATUS "Downloading ${URL} -> ${OUT}")
file(DOWNLOAD "${URL}" "${OUT}" SHOW_PROGRESS STATUS st TLS_VERIFY ON)
list(GET st 0 code)
if(NOT code EQUAL 0)
    message(WARNING "Download failed: ${st}")
    file(REMOVE "${OUT}")
endif()
