/**
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2025 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * World of Warcraft, and all World of Warcraft or Warcraft art, images,
 * and lore are copyrighted by Blizzard Entertainment, Inc.
 */

/**
 * This is part of the code that takes care of the Auction House and all that can happen with it,
 * it takes care of adding new items to it, bidding/buyouting them etc. Also handles the errors
 * that can happen, ie: you don't have enough money, your account isn't paid for (won't really
 * happen on these servers), the item you are trying to buy doesn't exist etc.
 *
 * This is also what is partly used by the \ref AuctionHouseBot as an interface to what it needs
 * for performing the usual operations such as checking what has been bidded on etc.
 *
 * \todo Add more info about how the auction house system works.
 */

#ifndef MANGOS_H_AUCTION_HOUSE_MGR
#define MANGOS_H_AUCTION_HOUSE_MGR

#include "Common.h"
#include "Policies/Singleton.h"
#include "DBCStructure.h"

#include <string>
#include <vector>

/** \addtogroup auctionhouse
 * @{
 * \file
 */

class Item;
class Player;
class Unit;
class WorldPacket;
struct CustodyDeferred;

#define MIN_AUCTION_TIME (2*HOUR)

/**
 * Documentation for this taken directly from comments in source
 * \todo Needs real documentation of what these values mean and where they are sent etc.
 */
enum AuctionError
{
    AUCTION_OK                          = 0,                ///< depends on enum AuctionAction
    AUCTION_ERR_INVENTORY               = 1,                ///< depends on enum InventoryChangeResult
    AUCTION_ERR_DATABASE                = 2,                ///< ERR_AUCTION_DATABASE_ERROR (default)
    AUCTION_ERR_NOT_ENOUGH_MONEY        = 3,                ///< ERR_NOT_ENOUGH_MONEY
    AUCTION_ERR_ITEM_NOT_FOUND          = 4,                ///< ERR_ITEM_NOT_FOUND
    AUCTION_ERR_HIGHER_BID              = 5,                ///< ERR_AUCTION_HIGHER_BID
    AUCTION_ERR_BID_INCREMENT           = 7,                ///< ERR_AUCTION_BID_INCREMENT
    AUCTION_ERR_BID_OWN                 = 10,               ///< ERR_AUCTION_BID_OWN
    AUCTION_ERR_RESTRICTED_ACCOUNT      = 13                ///< ERR_RESTRICTED_ACCOUNT
};

enum AuctionAction
{
    AUCTION_STARTED     = 0,                                ///< ERR_AUCTION_STARTED
    AUCTION_REMOVED     = 1,                                ///< ERR_AUCTION_REMOVED
    AUCTION_BID_PLACED  = 2                                 ///< ERR_AUCTION_BID_PLACED
};

struct AuctionEntry
{
    uint32 Id;
    uint32 itemGuidLow;                                     // can be 0 after send won mail with item
    uint32 itemTemplate;
    uint32 itemCount;
    int32 itemRandomPropertyId;
    uint32 owner;                                           // player low guid, can be 0 for server generated auction
    uint32 startbid;                                        // start minimal bid value
    uint32 bid;                                             // current bid, =0 meaning no bids
    uint32 buyout;
    time_t expireTime;
    uint32 bidder;                                          // current bidder player lowguid, can be 0 if bid generated by server, use 'bid'!=0 for check bid existance
    uint32 deposit;                                         // deposit can be calculated only when creating auction
    AuctionHouseEntry const* auctionHouseEntry;             // in AuctionHouse.dbc

    // helpers
    uint32 GetHouseId() const { return auctionHouseEntry->houseId; }
    uint32 GetHouseFaction() const { return auctionHouseEntry->faction; }
    uint32 GetAuctionCut() const;
    uint32 GetAuctionOutBid() const;
    bool BuildAuctionInfo(WorldPacket& data) const;
    void DeleteFromDB() const;
    void SaveToDB() const;
    void AuctionBidWinning(Player* bidder = NULL);
    /// Custody co-commit mirror of AuctionBidWinning: pays the seller, delivers
    /// the item to the winner, nets the deposit/bid ledger rows, deletes the
    /// auction row, and defers every in-memory effect (notifications, mail pushes,
    /// AH cache mutations, RemoveAuction, delete this) into @p def. Every DB write
    /// appends to the caller's ALREADY-OPEN CharacterDatabase transaction; the
    /// caller checked-commits it then runs @p def (spec Sec 6 S4). @p newbidder is
    /// the online winner (buyout path) or NULL (expiry path).
    ///
    /// @p knownBidKey is the idem_key of the live bid row to commit-net. It is
    /// REQUIRED on the buyout path: the bid row was just RESERVED in the same
    /// still-open transaction, so a synchronous SELECT (GetSingleLiveBidRow) cannot
    /// see it yet -- the caller passes the key it just reserved. On the expiry path
    /// the bid row is already committed, so the caller passes "" and this method
    /// re-fetches + validates it via GetSingleLiveBidRow. Ignored when bidder == 0.
    void AuctionBidWinningCustody(Player* newbidder, CustodyDeferred& def,
                                  std::string const& knownBidKey = "");
    /// Custody co-commit mirror of the unsold-expiry path (spec S6): returns the
    /// item to the seller by mail (or destroys it if the account is gone),
    /// forfeits the deposit to the house, deletes the auction row, and defers
    /// every in-memory effect (owner-expired notification, mail push, RemoveAItem,
    /// RemoveAuction, delete this) into @p def. Every DB write appends to the
    /// caller's ALREADY-OPEN CharacterDatabase transaction; the caller
    /// checked-commits it then runs @p def. S6 makes NO synchronous in-memory
    /// mutation, so on rollback there is nothing to restore.
    void ExpireUnsoldCustody(CustodyDeferred& def);
    bool UpdateBid(uint32 newbid, Player* newbidder = NULL);// true if normal bid, false if buyout, bidder==NULL for generated bid
    /// Custody co-commit mirror of UpdateBid: moves the bidder's gold via the
    /// custody primitives and appends every DB write to the caller's already-open
    /// CharacterDatabase transaction (the caller opens/commits it). Live effects
    /// (outbid notify/refund mail push) are queued into @p def. The outbid refund
    /// mail is sent via the static SendAuctionOutbiddedMailInTransaction, which
    /// resolves the old bidder's session itself, so no acting session is needed.
    ///
    /// @p liveBidKey is the idem_key of the existing live bid row, pre-fetched and
    /// VALIDATED by the handler before BeginTransaction (spec I1) for the
    /// same-bidder raise and the outbid-displacement cases; it is empty when the
    /// auction has no live bid row (bidder==0 / first bid). Used directly so this
    /// method never re-looks-up (and never trusts) an unvalidated row.
    ///
    /// A buyout (newbid >= buyout) is absorbed here (Task 10): the bid is capped at
    /// buyout, reserved/refunded as a normal bid, then the win resolves on the same
    /// open transaction via AuctionBidWinningCustody (auction delete + cache
    /// mutations deferred into @p def). Returns true if the auction remains active
    /// (normal bid), false on a buyout (auction resolved + scheduled for delete).
    bool UpdateBidCustody(uint32 newbid, Player* newbidder, CustodyDeferred& def,
                          std::string const& liveBidKey);
};

// this class is used as auctionhouse instance
class AuctionHouseObject
{
    public:
        AuctionHouseObject() {}
        ~AuctionHouseObject()
        {
            for (AuctionEntryMap::const_iterator itr = AuctionsMap.begin(); itr != AuctionsMap.end(); ++itr)
            {
                delete itr->second;
            }
        }

        typedef std::map<uint32, AuctionEntry*> AuctionEntryMap;
        typedef std::pair<AuctionEntryMap::const_iterator, AuctionEntryMap::const_iterator> AuctionEntryMapBounds;

        uint32 GetCount()
        {
            return AuctionsMap.size();
        }

        AuctionEntryMap const& GetAuctions() const { return AuctionsMap; }
        AuctionEntryMapBounds GetAuctionsBounds() const {return AuctionEntryMapBounds(AuctionsMap.begin(), AuctionsMap.end()); }

        void AddAuction(AuctionEntry* ah)
        {
            MANGOS_ASSERT(ah);
            AuctionsMap[ah->Id] = ah;
        }

        AuctionEntry* GetAuction(uint32 id) const
        {
            AuctionEntryMap::const_iterator itr = AuctionsMap.find(id);
            return itr != AuctionsMap.end() ? itr->second : NULL;
        }

        bool RemoveAuction(uint32 id)
        {
            return AuctionsMap.erase(id);
        }

        void Update();

        void BuildListBidderItems(WorldPacket& data, Player* player, uint32& count, uint32& totalcount);
        void BuildListOwnerItems(WorldPacket& data, Player* player, uint32& count, uint32& totalcount);
        void BuildListAuctionItems(WorldPacket& data, Player* player,
            std::wstring const& searchedname, uint32 listfrom, uint32 levelmin, uint32 levelmax, uint32 usable,
            uint32 inventoryType, uint32 itemClass, uint32 itemSubClass, uint32 quality,
            uint32& count, uint32& totalcount);

        /// Dispatcher for in-process browse fallback (C1/I1). Switches on @p kind:
        ///   0 = LIST (public browse), 1 = OWNER, 2 = BIDDER.
        /// For BIDDER the @p clientOutbidIds entries are prepended in CLIENT ORDER
        /// (matching HandleAuctionListBidderItems) before the sweep.
        /// All other parameters mirror the corresponding BuildList* signatures.
        void BuildListForKind(uint8 kind, WorldPacket& data, Player* player,
            const std::wstring& wname, uint32 listfrom, uint32 levelmin, uint32 levelmax,
            uint32 usable, uint32 invType, uint32 itemClass, uint32 itemSubClass,
            uint32 quality, const std::vector<uint32>& clientOutbidIds,
            uint32& count, uint32& totalcount);

        AuctionEntry* AddAuction(AuctionHouseEntry const* auctionHouseEntry, Item* newItem, uint32 etime, uint32 bid, uint32 buyout = 0, uint32 deposit = 0, Player* pl = NULL, bool ownTransaction = true);
        AuctionEntry* AddAuctionByGuid(AuctionHouseEntry const* auctionHouseEntry, Item* newItem, uint32 etime, uint32 bid, uint32 buyout, uint32 lowguid);
    private:
        AuctionEntryMap AuctionsMap;
};

/**
 * This describes the type of auction house that we are dealing with, they can be either:
 * - neutral (anyone can do their shopping there)
 * - alliance/horde (only the respective faction can shop there)
 */
enum AuctionHouseType
{
    AUCTION_HOUSE_ALLIANCE  = 0, ///< Alliance only auction house
    AUCTION_HOUSE_HORDE     = 1, ///< Horde only auction house
    AUCTION_HOUSE_NEUTRAL   = 2  ///< Neutral auction house, anyone can do business here
};

#define MAX_AUCTION_HOUSE_TYPE 3

class AuctionHouseMgr
{
    public:
        AuctionHouseMgr();
        ~AuctionHouseMgr();

        typedef UNORDERED_MAP<uint32, Item*> ItemMap;

        AuctionHouseObject* GetAuctionsMap(AuctionHouseType houseType) { return &mAuctions[houseType]; }
        AuctionHouseObject* GetAuctionsMap(AuctionHouseEntry const* house);

        Item* GetAItem(uint32 id)
        {
            ItemMap::const_iterator itr = mAitems.find(id);
            if (itr != mAitems.end())
            {
                return itr->second;
            }
            return NULL;
        }

        // auction messages
        void SendAuctionWonMail(AuctionEntry* auction);
        void SendAuctionSuccessfulMail(AuctionEntry* auction);
        void SendAuctionExpiredMail(AuctionEntry* auction);

        /// Custody co-commit variant of SendAuctionExpiredMail: same owner-exists
        /// guard + expired subject, but the item return mail co-commits into the
        /// caller's open transaction (no own Begin/Commit), the "item:<Id>" escrow
        /// row flips to TERMINAL_OK (DeliverItem on the return branch;
        /// CommitGoldLedgerOnly on the destroy branch), and the online owner's
        /// SMSG_AUCTION_OWNER_NOTIFICATION (expired form) + RemoveAItem (+ live
        /// item destroy on the no-owner branch) are deferred into @p def in legacy
        /// order (notify-then-mail, spec S6 / C7). itemGuidLow is intentionally NOT
        /// zeroed (success deletes the AuctionEntry; rollback needs the GUID).
        void SendAuctionExpiredMailInTransaction(AuctionEntry* auction, CustodyDeferred& def);

        /// Custody co-commit variant of SendAuctionSuccessfulMail: same owner-exists
        /// guard + profit math, but the seller payout mail co-commits into the
        /// caller's open transaction (no own Begin/Commit) and the online owner-sold
        /// notification is deferred into @p def BEFORE the mail push so packet order
        /// stays notify-then-mail (legacy). Reads auction->bid/bidder, so the caller
        /// MUST call this before mutating them (spec S4 / B).
        void SendAuctionSuccessfulMailInTransaction(AuctionEntry* auction, CustodyDeferred& def);

        /// Custody co-commit variant of SendAuctionWonMail: keeps the GM-log block;
        /// the item_instance owner UPDATE (receiver-exists) or DELETE (destroy)
        /// appends to the caller's open transaction, the winner mail co-commits via
        /// SendMailToInTransaction, and the bidder notification + RemoveAItem +
        /// itemGuidLow=0 (+ live item destroy on the no-receiver branch) are deferred
        /// into @p def in legacy order (spec S4 / C).
        void SendAuctionWonMailInTransaction(AuctionEntry* auction, CustodyDeferred& def);
        static uint32 GetAuctionDeposit(AuctionHouseEntry const* entry, uint32 time, Item* pItem);

        static uint32 GetAuctionHouseTeam(AuctionHouseEntry const* house);
        static AuctionHouseEntry const* GetAuctionHouseEntry(Unit* unit);

    public:
        // load first auction items, because of check if item exists, when loading
        void LoadAuctionItems();
        void LoadAuctions();

        void AddAItem(Item* it);
        bool RemoveAItem(uint32 id);

        void Update();

    private:
        AuctionHouseObject  mAuctions[MAX_AUCTION_HOUSE_TYPE];

        ItemMap             mAitems;
};

/// Convenience define to access the singleton object for the Auction House Manager
#define sAuctionMgr MaNGOS::Singleton<AuctionHouseMgr>::Instance()

/// Test seam for the client-outbid-prepend order contract (used by -t ahbrowsehelper).
/// Records the ids from @p clientIds into @p outOrder in CLIENT ORDER, locking
/// the invariant that BuildListForKind(BIDDER) prepends them before the sweep.
void AhAppendClientOutbidsForTest(const std::vector<uint32>& clientIds,
                                  std::vector<uint32>& outOrder);

/** @} */

#endif
