#ifndef DBCSTRUCTURE_REFERENCE_H
#define DBCSTRUCTURE_REFERENCE_H

// AUTO-GENERATED by CoreAlign/tools/gen_reference.py — DO NOT EDIT.
// Inert reference map of the client DBC tables the core does NOT model.
// This header is never #included; activating a table = move its struct into
// DBCStructure.h, add its fmt to DBCfmt.h, and a DBCStorage loader.

/*
 * DBC MAP — 154 client 1.12 tables (build 1.12.1.5875)
 *   ACTIVE = modelled + loaded in DBCStructure.h ; DOC = inert reference here.
 *
 *   AnimationData            DOC   (7 cols)
 *   AreaPOI                  DOC   (29 cols)
 *   AreaTable                ACTIVE
 *   AreaTrigger              ACTIVE
 *   AttackAnimKits           DOC   (5 cols)
 *   AttackAnimTypes          DOC   (2 cols)
 *   AuctionHouse             ACTIVE
 *   BankBagSlotPrices        ACTIVE
 *   CameraShakes             DOC   (8 cols)
 *   Cfg_Categories           DOC   (11 cols)
 *   Cfg_Configs              DOC   (4 cols)
 *   CharBaseInfo             DOC   (2 cols)
 *   CharHairGeosets          DOC   (6 cols)
 *   CharHairTextures         DOC   (8 cols)
 *   CharSections             DOC   (10 cols)
 *   CharStartOutfit          ACTIVE
 *   CharVariations           DOC   (6 cols)
 *   CharacterFacialHairStyles DOC   (9 cols)
 *   ChatChannels             ACTIVE
 *   ChatProfanity            DOC   (2 cols)
 *   ChrClasses               ACTIVE
 *   ChrRaces                 ACTIVE
 *   CinematicCamera          DOC   (7 cols)
 *   CinematicSequences       ACTIVE
 *   CreatureDisplayInfo      ACTIVE
 *   CreatureDisplayInfoExtra ACTIVE
 *   CreatureFamily           ACTIVE
 *   CreatureModelData        DOC   (16 cols)
 *   CreatureSoundData        DOC   (30 cols)
 *   CreatureSpellData        ACTIVE
 *   CreatureType             ACTIVE
 *   DeathThudLookups         DOC   (5 cols)
 *   DurabilityCosts          ACTIVE
 *   DurabilityQuality        ACTIVE
 *   Emotes                   ACTIVE
 *   EmotesText               ACTIVE
 *   EmotesTextData           DOC   (10 cols)
 *   EmotesTextSound          DOC   (5 cols)
 *   EnvironmentalDamage      DOC   (3 cols)
 *   Exhaustion               DOC   (15 cols)
 *   Faction                  ACTIVE
 *   FactionGroup             DOC   (12 cols)
 *   FactionTemplate          ACTIVE
 *   FootprintTextures        DOC   (2 cols)
 *   FootstepTerrainLookup    DOC   (5 cols)
 *   GMSurveyCurrentSurvey    DOC   (2 cols)
 *   GMSurveyQuestions        DOC   (10 cols)
 *   GMSurveySurveys          DOC   (11 cols)
 *   GMTicketCategory         DOC   (10 cols)
 *   GameObjectArtKit         DOC   (8 cols)
 *   GameObjectDisplayInfo    ACTIVE
 *   GameTips                 DOC   (10 cols)
 *   GroundEffectDoodad       DOC   (3 cols)
 *   GroundEffectTexture      DOC   (7 cols)
 *   HelmetGeosetVisData      DOC   (6 cols)
 *   ItemBagFamily            ACTIVE
 *   ItemClass                ACTIVE
 *   ItemDisplayInfo          DOC   (23 cols)
 *   ItemGroupSounds          DOC   (5 cols)
 *   ItemPetFood              DOC   (10 cols)
 *   ItemRandomProperties     ACTIVE
 *   ItemSet                  ACTIVE
 *   ItemSubClass             DOC   (28 cols)
 *   ItemSubClassMask         DOC   (11 cols)
 *   ItemVisualEffects        DOC   (2 cols)
 *   ItemVisuals              DOC   (6 cols)
 *   LanguageWords            DOC   (3 cols)
 *   Languages                DOC   (10 cols)
 *   LfgDungeons              DOC   (14 cols)
 *   Light                    DOC   (12 cols)
 *   LightFloatBand           DOC   (34 cols)
 *   LightIntBand             DOC   (34 cols)
 *   LightParams              DOC   (9 cols)
 *   LightSkybox              DOC   (2 cols)
 *   LiquidType               ACTIVE
 *   LoadingScreenTaxiSplines DOC   (19 cols)
 *   LoadingScreens           DOC   (3 cols)
 *   Lock                     ACTIVE
 *   LockType                 DOC   (29 cols)
 *   MailTemplate             ACTIVE
 *   Map                      ACTIVE
 *   Material                 DOC   (3 cols)
 *   NPCSounds                DOC   (5 cols)
 *   NameGen                  DOC   (4 cols)
 *   NamesProfanity           DOC   (2 cols)
 *   NamesReserved            DOC   (2 cols)
 *   Package                  DOC   (12 cols)
 *   PageTextMaterial         DOC   (2 cols)
 *   PaperDollItemFrame       DOC   (3 cols)
 *   PetLoyalty               DOC   (10 cols)
 *   PetPersonality           DOC   (19 cols)
 *   QuestInfo                DOC   (10 cols)
 *   QuestSort                ACTIVE
 *   Resistances              DOC   (12 cols)
 *   ServerMessages           DOC   (10 cols)
 *   SheatheSoundLookups      DOC   (7 cols)
 *   SkillCostsData           DOC   (5 cols)
 *   SkillLine                ACTIVE
 *   SkillLineAbility         ACTIVE
 *   SkillLineCategory        DOC   (11 cols)
 *   SkillRaceClassInfo       ACTIVE
 *   SkillTiers               DOC   (33 cols)
 *   SoundAmbience            DOC   (3 cols)
 *   SoundEntries             ACTIVE
 *   SoundProviderPreferences DOC   (24 cols)
 *   SoundSamplePreferences   DOC   (17 cols)
 *   SoundWaterType           DOC   (4 cols)
 *   SpamMessages             DOC   (2 cols)
 *   Spell                    ACTIVE
 *   SpellCastTimes           ACTIVE
 *   SpellCategory            DOC   (2 cols)
 *   SpellChainEffects        DOC   (8 cols)
 *   SpellDispelType          DOC   (12 cols)
 *   SpellDuration            ACTIVE
 *   SpellEffectCameraShakes  DOC   (4 cols)
 *   SpellFocusObject         ACTIVE
 *   SpellIcon                DOC   (2 cols)
 *   SpellItemEnchantment     ACTIVE
 *   SpellMechanic            DOC   (10 cols)
 *   SpellRadius              ACTIVE
 *   SpellRange               ACTIVE
 *   SpellShapeshiftForm      ACTIVE
 *   SpellVisual              DOC   (16 cols)
 *   SpellVisualEffectName    DOC   (5 cols)
 *   SpellVisualKit           DOC   (35 cols)
 *   SpellVisualPrecastTransitions DOC   (3 cols)
 *   StableSlotPrices         ACTIVE
 *   Startup_Strings          DOC   (11 cols)
 *   Stationery               DOC   (4 cols)
 *   StringLookups            DOC   (2 cols)
 *   Talent                   ACTIVE
 *   TalentTab                ACTIVE
 *   TaxiNodes                ACTIVE
 *   TaxiPath                 ACTIVE
 *   TaxiPathNode             ACTIVE
 *   TerrainType              DOC   (6 cols)
 *   TerrainTypeSounds        DOC   (1 cols)
 *   TransportAnimation       DOC   (7 cols)
 *   UISoundLookups           DOC   (3 cols)
 *   UnitBlood                DOC   (10 cols)
 *   UnitBloodLevels          DOC   (4 cols)
 *   VideoHardware            DOC   (22 cols)
 *   VocalUISounds            DOC   (7 cols)
 *   WMOAreaTable             ACTIVE
 *   WeaponImpactSounds       DOC   (23 cols)
 *   WeaponSwingSounds2       DOC   (4 cols)
 *   WorldMapArea             ACTIVE
 *   WorldMapContinent        DOC   (13 cols)
 *   WorldMapOverlay          DOC   (17 cols)
 *   WorldSafeLocs            ACTIVE
 *   WorldStateUI             DOC   (39 cols)
 *   WowError_Strings         DOC   (11 cols)
 *   ZoneIntroMusicTable      DOC   (5 cols)
 *   ZoneMusic                DOC   (8 cols)
 *
 *   (51 ACTIVE, 103 DOC)
 */

// AnimationData — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct AnimationDataEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  Weaponflags;  // 2
    uint32  Bodyflags;  // 3
    int32   Field_0_7_0_3694_004;  // [dbd-only] 4
    uint32  Flags;  // 5
    uint32  Fallback;  // 6
};

// AreaPOI — 29 cols, record_size 116, build 1.12.1.5875. INERT reference (not loaded).
struct AreaPOIEntry
{
    uint32  ID;  // 0
    int32   Importance;  // 1
    int32   Icon;  // 2
    int32   FactionID;  // [dbd-only] 3
    float   Pos[3];  // [dbd-only] 4-6
    int32   ContinentID;  // 7
    uint32  Flags;  // 8
    int32   AreaID;  // 9
    char*   Name_lang[8];  // 10-17
// uint32  Name_lang_flags;  // [dbd-only] 18
    char*   Description_lang[8];  // 19-26
// uint32  Description_lang_flags;  // [dbd-only] 27
    int32   WorldStateID;  // 28
};

// AttackAnimKits — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct AttackAnimKitsEntry
{
    uint32  ID;  // 0
    int32   ItemSubclassID;  // 1
    int32   AnimTypeID;  // 2
    int32   AnimFrequency;  // 3
    int32   WhichHand;  // 4
};

// AttackAnimTypes — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct AttackAnimTypesEntry
{
    uint32  AnimID;  // 0
    char*   AnimName;  // 1
};

// CameraShakes — 8 cols, record_size 32, build 1.12.1.5875. INERT reference (not loaded).
struct CameraShakesEntry
{
    uint32  ID;  // 0
    int32   ShakeType;  // 1
    uint32  Direction;  // 2
    float   Amplitude;  // 3
    float   Frequency;  // 4
    float   Duration;  // 5
    float   Phase;  // 6
    float   Coefficient;  // 7
};

// Cfg_Categories — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct Cfg_CategoriesEntry
{
    uint32  ID;  // 0
    uint32  Region;  // 1
    char*   Name_lang[8];  // 2-9
// uint32  Name_lang_flags;  // 10
};

// Cfg_Configs — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct Cfg_ConfigsEntry
{
    uint32  ID;  // 0
    uint32  RealmType;  // 1
    uint32  PlayerKillingAllowed;  // 2
    uint32  Roleplaying;  // 3
};

// CharBaseInfo — 2 cols, record_size 2, build 1.12.1.5875. INERT reference (not loaded).
struct CharBaseInfoEntry
{
    uint8   RaceID;  // 0
    uint8   ClassID;  // 1
};

// CharHairGeosets — 6 cols, record_size 24, build 1.12.1.5875. INERT reference (not loaded).
struct CharHairGeosetsEntry
{
    uint32  ID;  // 0
    uint32  RaceID;  // 1
    uint32  SexID;  // 2
    uint32  VariationID;  // 3
    uint32  GeosetID;  // 4
    uint32  Showscalp;  // [dbd-only] 5
};

// CharHairTextures — 8 cols, record_size 32, build 1.12.1.5875. INERT reference (not loaded).
struct CharHairTexturesEntry
{
    int32   ID;  // 0
    int32   Field_0_5_3_3368_001_race;  // 1
    int32   Field_0_5_3_3368_002_gender;  // 2
    int32   Field_0_5_3_3368_003;  // 3
    int32   Field_0_5_3_3368_004_mayberacemask;  // 4
    int32   Field_0_5_3_3368_005_the_x_in_hair_xy_blp;  // 5
    int32   Field_0_5_3_3368_006;  // 6
    int32   Field_0_5_3_3368_007;  // 7
};

// CharSections — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct CharSectionsEntry
{
    uint32  ID;  // 0
    uint32  RaceID;  // 1
    uint32  SexID;  // 2
    uint32  BaseSection;  // 3
    uint32  VariationIndex;  // 4
    uint32  ColorIndex;  // 5
    char*   TextureName[3];  // 6-8
    uint32  Flags;  // 9
};

// CharVariations — 6 cols, record_size 24, build 1.12.1.5875. INERT reference (not loaded).
struct CharVariationsEntry
{
    uint32  RaceID;  // 0
    uint32  SexID;  // 1
    uint32  TextureHoldLayer[4];  // [dbd-only] 2-5
};

// CharacterFacialHairStyles — 9 cols, record_size 36, build 1.12.1.5875. INERT reference (not loaded).
struct CharacterFacialHairStylesEntry
{
    uint32  ID;  // 0
    uint32  RaceID;  // 1
    uint32  SexID;  // 2
    uint32  VariationID;  // [dbd-only] 3
    uint32  Geoset1;  // [dbd-only] 4
    uint32  Geoset2;  // [dbd-only] 5
    uint32  BeardGeoset;  // 6
    uint32  MoustacheGeoset;  // 7
    uint32  SideburnGeoset;  // 8
};

// ChatProfanity — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct ChatProfanityEntry
{
    int32   ID;  // 0
    char*   Text;  // 1
};

// CinematicCamera — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct CinematicCameraEntry
{
    uint32  ID;  // 0
    char*   Model;  // 1
    uint32  SoundID;  // 2
    float   OriginX;  // 3
    float   OriginY;  // 4
    float   OriginZ;  // 5
    float   OriginFacing;  // 6
};

// CreatureModelData — 16 cols, record_size 64, build 1.12.1.5875. INERT reference (not loaded).
struct CreatureModelDataEntry
{
    uint32  ID;  // 0
    int32   Flags;  // 1
    char*   ModelName;  // 2
    int32   SizeClass;  // [dbd-only] 3
    float   ModelScale;  // [dbd-only] 4
    int32   BloodID;  // 5
    int32   FootprintTextureID;  // 6
    float   FootprintTextureLength;  // 7
    float   FootprintTextureWidth;  // 8
    float   FootprintParticleScale;  // [dbd-only] 9
    int32   FoleyMaterialID;  // [dbd-only] 10
    int32   FootstepShakeSize;  // [dbd-only] 11
    int32   DeathThudShakeSize;  // [dbd-only] 12
    int32   SoundID;  // 13
    float   CollisionWidth;  // 14
    float   CollisionHeight;  // 15
};

// CreatureSoundData — 30 cols, record_size 120, build 1.12.1.5875. INERT reference (not loaded).
struct CreatureSoundDataEntry
{
    uint32  ID;  // 0
    uint32  SoundExertionID;  // 1
    uint32  SoundExertionCriticalID;  // 2
    uint32  SoundInjuryID;  // 3
    uint32  SoundInjuryCriticalID;  // 4
    uint32  SoundInjuryCrushingBlowID;  // 5
    uint32  SoundDeathID;  // 6
    uint32  SoundStunID;  // 7
    uint32  SoundStandID;  // 8
    uint32  SoundFootstepID;  // 9
    uint32  SoundAggroID;  // 10
    uint32  SoundWingFlapID;  // 11
    uint32  SoundWingGlideID;  // 12
    uint32  SoundAlertID;  // 13
    uint32  SoundFidget[4];  // 14-17
    uint32  CustomAttack[4];  // 18-21
    uint32  NPCSoundID;  // 22
    uint32  LoopSoundID;  // 23
    uint32  CreatureImpactType;  // 24
    uint32  SoundJumpStartID;  // 25
    uint32  SoundJumpEndID;  // 26
    uint32  SoundPetAttackID;  // 27
    uint32  SoundPetOrderID;  // 28
    uint32  SoundPetDismissID;  // 29
};

// DeathThudLookups — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct DeathThudLookupsEntry
{
    uint32  ID;  // 0
    uint32  SizeClass;  // 1
    uint32  TerrainTypeSoundID;  // [dbd-only] 2
    uint32  SoundEntryID;  // 3
    uint32  SoundEntryIDWater;  // 4
};

// EmotesTextData — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct EmotesTextDataEntry
{
    uint32  ID;  // 0
    char*   Text_lang[8];  // 1-8
// uint32  Text_lang_flags;  // 9
};

// EmotesTextSound — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct EmotesTextSoundEntry
{
    uint32  ID;  // 0
    uint32  EmotesTextID;  // 1
    uint32  RaceID;  // 2
    uint32  SexID;  // 3
    uint32  SoundID;  // 4
};

// EnvironmentalDamage — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct EnvironmentalDamageEntry
{
    uint32  ID;  // [dbd-only] 0
    uint32  EnumID;  // 1
    int32   VisualkitID;  // 2
};

// Exhaustion — 15 cols, record_size 60, build 1.12.1.5875. INERT reference (not loaded).
struct ExhaustionEntry
{
    uint32  ID;  // 0
    int32   Xp;  // 1
    float   Factor;  // 2
    float   OutdoorHours;  // 3
    float   InnHours;  // 4
    char*   Name_lang[8];  // 5-12
// uint32  Name_lang_flags;  // 13
    float   Threshold;  // 14
};

// FactionGroup — 12 cols, record_size 48, build 1.12.1.5875. INERT reference (not loaded).
struct FactionGroupEntry
{
    uint32  ID;  // 0
    uint32  MaskID;  // 1
    char*   InternalName;  // 2
    char*   Name_lang[8];  // 3-10
// uint32  Name_lang_flags;  // 11
};

// FootprintTextures — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct FootprintTexturesEntry
{
    uint32  ID;  // 0
    char*   FootstepFilename;  // 1
};

// FootstepTerrainLookup — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct FootstepTerrainLookupEntry
{
    uint32  ID;  // 0
    uint32  CreatureFootstepID;  // 1
    uint32  TerrainSoundID;  // 2
    uint32  SoundID;  // 3
    uint32  SoundIDSplash;  // 4
};

// GMSurveyCurrentSurvey — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct GMSurveyCurrentSurveyEntry
{
    uint32  LangID;  // 0
    uint32  GMSurveyID;  // 1
};

// GMSurveyQuestions — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct GMSurveyQuestionsEntry
{
    uint32  ID;  // 0
    char*   Question_lang[8];  // 1-8
// uint32  Question_lang_flags;  // 9
};

// GMSurveySurveys — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct GMSurveySurveysEntry
{
    int32   ID;  // 0
    int32   Q[10];  // 1-10
};

// GMTicketCategory — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct GMTicketCategoryEntry
{
    uint32  ID;  // 0
    char*   Category_lang[8];  // [dbd-only] 1-8
// uint32  Category_lang_flags;  // [dbd-only] 9
};

// GameObjectArtKit — 8 cols, record_size 32, build 1.12.1.5875. INERT reference (not loaded).
struct GameObjectArtKitEntry
{
    int32   ID;  // 0
    char*   TextureVariation[3];  // 1-3
    char*   AttachModel[4];  // 4-7
};

// GameTips — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct GameTipsEntry
{
    uint32  ID;  // 0
    char*   Text_lang[8];  // 1-8
// uint32  Text_lang_flags;  // 9
};

// GroundEffectDoodad — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct GroundEffectDoodadEntry
{
    uint32  ID;  // 0
    uint32  DoodadIdTag;  // 1
    char*   Doodadpath;  // 2
};

// GroundEffectTexture — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct GroundEffectTextureEntry
{
    uint32  ID;  // 0
    int32   DoodadID[4];  // [dbd-only] 1-4
    int32   Density;  // [dbd-only] 5
    int32   Sound;  // [dbd-only] 6
};

// HelmetGeosetVisData — 6 cols, record_size 24, build 1.12.1.5875. INERT reference (not loaded).
struct HelmetGeosetVisDataEntry
{
    uint32  ID;  // 0
    uint32  HideGeoset[5];  // 1-5
};

// ItemDisplayInfo — 23 cols, record_size 92, build 1.12.1.5875. INERT reference (not loaded).
struct ItemDisplayInfoEntry
{
    uint32  ID;  // 0
    char*   ModelName[2];  // 1-2
    char*   ModelTexture[2];  // 3-4
    char*   InventoryIcon;  // 5
    int32   GeosetGroup[3];  // 6-8
    uint32  Flags;  // 9
    int32   SpellVisualID;  // 10
    int32   GroupSoundIndex;  // 11
    int32   HelmetGeosetVisID[2];  // 12-13
    char*   Texture[8];  // 14-21
    int32   ItemVisual;  // 22
};

// ItemGroupSounds — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct ItemGroupSoundsEntry
{
    uint32  ID;  // 0
    uint32  Sound_1;  // 1
    uint32  Sound_2;  // 2
    uint32  Sound_3;  // 3
    uint32  Sound_4;  // 4
};

// ItemPetFood — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct ItemPetFoodEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
};

// ItemSubClass — 28 cols, record_size 112, build 1.12.1.5875. INERT reference (not loaded).
struct ItemSubClassEntry
{
    int32   ClassID;  // 0
    uint32  SubClassID;  // 1
    int32   PrerequisiteProficiency;  // 2
    int32   PostrequisiteProficiency;  // 3
    uint32  Flags;  // 4
    uint32  DisplayFlags;  // 5
    int32   WeaponParrySeq;  // 6
    int32   WeaponReadySeq;  // 7
    int32   WeaponAttackSeq;  // 8
    int32   WeaponSwingSize;  // 9
    char*   DisplayName_lang[8];  // 10-17
// uint32  DisplayName_lang_flags;  // 18
    char*   VerboseName_lang[8];  // 19-26
// uint32  VerboseName_lang_flags;  // 27
};

// ItemSubClassMask — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct ItemSubClassMaskEntry
{
    uint32  ClassID;  // 0
    uint32  Mask;  // 1
    char*   Name_lang[8];  // 2-9
// uint32  Name_lang_flags;  // 10
};

// ItemVisualEffects — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct ItemVisualEffectsEntry
{
    uint32  ID;  // 0
    char*   Model;  // 1
};

// ItemVisuals — 6 cols, record_size 24, build 1.12.1.5875. INERT reference (not loaded).
struct ItemVisualsEntry
{
    uint32  ID;  // 0
    uint32  Effect1;  // 1
    uint32  Effect2;  // 2
    uint32  Effect3;  // 3
    uint32  Effect4;  // 4
    uint32  Effect5;  // 5
};

// LanguageWords — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct LanguageWordsEntry
{
    uint32  ID;  // 0
    uint32  LanguageID;  // 1
    char*   Word;  // 2
};

// Languages — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct LanguagesEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
};

// LfgDungeons — 14 cols, record_size 56, build 1.12.1.5875. INERT reference (not loaded).
struct LfgDungeonsEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // [dbd-only] 9
    int32   MinLevel;  // 10
    int32   MaxLevel;  // 11
    int32   TypeID;  // 12
    int32   Faction;  // 13
};

// Light — 12 cols, record_size 48, build 1.12.1.5875. INERT reference (not loaded).
struct LightEntry
{
    uint32  ID;  // 0
    uint32  ContinentID;  // 1
    float   GameCoords[3];  // 2-4
    float   GameFalloffStart;  // 5
    float   GameFalloffEnd;  // 6
    int32   LightParamsID[5];  // 7-11
};

// LightFloatBand — 34 cols, record_size 136, build 1.12.1.5875. INERT reference (not loaded).
struct LightFloatBandEntry
{
    uint32  ID;  // 0
    int32   Num;  // 1
    int32   Time[16];  // 2-17
    float   Data[16];  // 18-33
};

// LightIntBand — 34 cols, record_size 136, build 1.12.1.5875. INERT reference (not loaded).
struct LightIntBandEntry
{
    uint32  ID;  // 0
    int32   Num;  // 1
    int32   Time[16];  // 2-17
    uint32  Data[16];  // 18-33
};

// LightParams — 9 cols, record_size 36, build 1.12.1.5875. INERT reference (not loaded).
struct LightParamsEntry
{
    uint32  ID;  // 0
    int32   HighlightSky;  // 1
    uint32  LightSkyboxID;  // 2
    float   Glow;  // [dbd-only] 3
    float   WaterShallowAlpha;  // 4
    float   WaterDeepAlpha;  // 5
    float   OceanShallowAlpha;  // 6
    float   OceanDeepAlpha;  // 7
    float   Flags;  // 8
};

// LightSkybox — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct LightSkyboxEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// LoadingScreenTaxiSplines — 19 cols, record_size 76, build 1.12.1.5875. INERT reference (not loaded).
struct LoadingScreenTaxiSplinesEntry
{
    uint32  ID;  // 0
    uint32  PathID;  // 1
    float   Locx[8];  // 2-9
    float   Locy[8];  // 10-17
    int32   LegIndex;  // 18
};

// LoadingScreens — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct LoadingScreensEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    char*   FileName;  // 2
};

// LockType — 29 cols, record_size 116, build 1.12.1.5875. INERT reference (not loaded).
struct LockTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
    char*   ResourceName_lang[8];  // 10-17
// uint32  ResourceName_lang_flags;  // 18
    char*   Verb_lang[8];  // 19-26
// uint32  Verb_lang_flags;  // 27
    char*   CursorName;  // 28
};

// Material — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct MaterialEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
    uint32  FoleySoundID;  // 2
};

// NPCSounds — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct NPCSoundsEntry
{
    uint32  ID;  // 0
    uint32  SoundID_1;  // 1
    uint32  SoundID_2;  // 2
    uint32  SoundID_3;  // 3
    uint32  SoundID_4;  // 4
};

// NameGen — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct NameGenEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  RaceID;  // 2
    uint32  Sex;  // 3
};

// NamesProfanity — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct NamesProfanityEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// NamesReserved — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct NamesReservedEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// Package — 12 cols, record_size 48, build 1.12.1.5875. INERT reference (not loaded).
struct PackageEntry
{
    uint32  ID;  // 0
    char*   Icon;  // 1
    int32   Cost;  // 2
    char*   Name_lang_loc1;  // 3
    char*   Name_lang_loc2;  // 4
    char*   Name_lang_loc3;  // 5
    char*   Name_lang_loc4;  // 6
    char*   Name_lang_loc5;  // 7
    char*   Name_lang_loc6;  // 8
    char*   Name_lang_loc7;  // 9
    char*   Name_lang_loc8;  // 10
    uint32  Name_lang_flags;  // [dbd-only] 11
};

// PageTextMaterial — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct PageTextMaterialEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// PaperDollItemFrame — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct PaperDollItemFrameEntry
{
    char*   ItemButtonName;  // 0
    char*   SlotIcon;  // 1
    int32   SlotNumber;  // 2
};

// PetLoyalty — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct PetLoyaltyEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
};

// PetPersonality — 19 cols, record_size 76, build 1.12.1.5875. INERT reference (not loaded).
struct PetPersonalityEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
    int32   HappinessThreshold[3];  // 10-12
    float   HappinessDamage[3];  // 13-15
    float   DamageModifier[3];  // 16-18
};

// QuestInfo — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct QuestInfoEntry
{
    uint32  ID;  // 0
    char*   InfoName_lang[8];  // 1-8
// uint32  InfoName_lang_flags;  // 9
};

// Resistances — 12 cols, record_size 48, build 1.12.1.5875. INERT reference (not loaded).
struct ResistancesEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
    uint32  FizzleSoundID;  // 2
    char*   Name_lang[8];  // 3-10
// uint32  Name_lang_flags;  // 11
};

// ServerMessages — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct ServerMessagesEntry
{
    uint32  ID;  // 0
    char*   Text_lang[8];  // [dbd-only] 1-8
// uint32  Text_lang_flags;  // 9
};

// SheatheSoundLookups — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct SheatheSoundLookupsEntry
{
    uint32  ID;  // 0
    uint32  ClassID;  // 1
    uint32  SubclassID;  // [dbd-only] 2
    uint32  Material;  // 3
    uint32  CheckMaterial;  // 4
    uint32  SheatheSound;  // 5
    uint32  UnsheatheSound;  // 6
};

// SkillCostsData — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct SkillCostsDataEntry
{
    uint32  ID;  // 0
    uint32  SkillCostsID;  // 1
    int32   Cost1;  // [dbd-only] 2
    int32   Cost2;  // [dbd-only] 3
    int32   Cost3;  // [dbd-only] 4
};

// SkillLineCategory — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct SkillLineCategoryEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
    int32   SortIndex;  // [dbd-only] 10
};

// SkillTiers — 33 cols, record_size 132, build 1.12.1.5875. INERT reference (not loaded).
struct SkillTiersEntry
{
    uint32  ID;  // 0
    int32   Cost[16];  // 1-16
    int32   Value[16];  // 17-32
};

// SoundAmbience — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct SoundAmbienceEntry
{
    uint32  ID;  // 0
    uint32  AmbienceID[2];  // 1-2
};

// SoundProviderPreferences — 24 cols, record_size 96, build 1.12.1.5875. INERT reference (not loaded).
struct SoundProviderPreferencesEntry
{
    uint32  ID;  // 0
    char*   Description;  // 1
    uint32  Flags;  // 2
    uint32  EAXEnvironmentSelection;  // 3
    float   EAXDecayTime;  // 4
    float   EAX2EnvironmentSize;  // 5
    float   EAX2EnvironmentDiffusion;  // 6
    int32   EAX2Room;  // 7
    int32   EAX2RoomHF;  // 8
    float   EAX2DecayHFRatio;  // 9
    int32   EAX2Reflections;  // 10
    float   EAX2ReflectionsDelay;  // 11
    int32   EAX2Reverb;  // 12
    float   EAX2ReverbDelay;  // 13
    float   EAX2RoomRolloff;  // 14
    float   EAX2AirAbsorption;  // 15
    int32   EAX3RoomLF;  // 16
    float   EAX3DecayLFRatio;  // 17
    float   EAX3EchoTime;  // 18
    float   EAX3EchoDepth;  // 19
    float   EAX3ModulationTime;  // 20
    float   EAX3ModulationDepth;  // 21
    float   EAX3HFReference;  // 22
    float   EAX3LFReference;  // 23
};

// SoundSamplePreferences — 17 cols, record_size 68, build 1.12.1.5875. INERT reference (not loaded).
struct SoundSamplePreferencesEntry
{
    uint32  ID;  // 0
    int32   EAX2SampleDirect;  // 1
    int32   EAX2SampleDirectHF;  // 2
    int32   EAX2SampleRoom;  // 3
    int32   EAX2SampleRoomHF;  // 4
    float   EAX2SampleObstruction;  // 5
    float   EAX2SampleObstructionLFRatio;  // 6
    float   EAX2SampleOcclusion;  // 7
    float   EAX2SampleOcclusionLFRatio;  // 8
    float   EAX2SampleOcclusionRoomRatio;  // 9
    float   EAX2SampleRoomRolloffFactor;  // 10
    float   EAX2SampleAirAbsorptionFactor;  // 11
    int32   EAX2SampleOutsideVolumeHF;  // 12
    float   EAX3SampleOcclusionDirectRatio;  // 13
    float   EAX3SampleExclusion;  // 14
    float   EAX3SampleExclusionLFRatio;  // 15
    float   EAX3SampleDopplerFactor;  // 16
};

// SoundWaterType — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct SoundWaterTypeEntry
{
    uint32  ID;  // 0
    uint32  SoundType;  // 1
    uint32  SoundSubtype;  // 2
    uint32  SoundID;  // 3
};

// SpamMessages — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct SpamMessagesEntry
{
    uint32  ID;  // 0
    char*   Text;  // 1
};

// SpellCategory — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct SpellCategoryEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // [dbd-only] 1
};

// SpellChainEffects — 8 cols, record_size 32, build 1.12.1.5875. INERT reference (not loaded).
struct SpellChainEffectsEntry
{
    uint32  ID;  // 0
    float   AvgSegLen;  // 1
    float   Width;  // 2
    float   NoiseScale;  // 3
    float   TexCoordScale;  // 4
    int32   SegDuration;  // 5
    int32   SegDelay;  // 6
    char*   Texture;  // 7
};

// SpellDispelType — 12 cols, record_size 48, build 1.12.1.5875. INERT reference (not loaded).
struct SpellDispelTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[8];  // 1-8
// uint32  Name_lang_flags;  // 9
    uint32  Mask;  // 10
    char*   InternalName;  // 11
};

// SpellEffectCameraShakes — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct SpellEffectCameraShakesEntry
{
    uint32  ID;  // 0
    uint32  CameraShake_1;  // [dbd-only] 1
    uint32  CameraShake_2;  // [dbd-only] 2
    uint32  CameraShake_3;  // [dbd-only] 3
};

// SpellIcon — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct SpellIconEntry
{
    uint32  ID;  // 0
    char*   TextureFilename;  // 1
};

// SpellMechanic — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct SpellMechanicEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   StateName_lang[8];  // [dbd-only] 1-8
// uint32  StateName_lang_flags;  // [dbd-only] 9
};

// SpellVisual — 16 cols, record_size 64, build 1.12.1.5875. INERT reference (not loaded).
struct SpellVisualEntry
{
    uint32  ID;  // 0
    uint32  PrecastKit;  // 1
    uint32  CastKit;  // 2
    uint32  ImpactKit;  // 3
    uint32  StateKit;  // 4
    uint32  ChannelKit;  // 5
    uint32  HasMissile;  // 6
    uint32  MissileModel;  // 7
    uint32  MissilePathType;  // 8
    uint32  MissileDestinationAttachment;  // 9
    uint32  MissileSound;  // 10
    uint32  HasAreaEffect;  // 11
    uint32  AreaModel;  // 12
    uint32  AreaKit;  // 13
    uint32  AnimEventSoundID;  // 14
    uint32  Flags;  // [dbd-only] 15
};

// SpellVisualEffectName — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct SpellVisualEffectNameEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    char*   FileName;  // 2
    int32   SpecialAttachPoint;  // [dbd-only] 3
    float   AreaEffectSize;  // [dbd-only] 4
};

// SpellVisualKit — 35 cols, record_size 140, build 1.12.1.5875. INERT reference (not loaded).
struct SpellVisualKitEntry
{
    uint32  ID;  // 0
    int32   KitType;  // [dbd-only] 1
    int32   AnimID;  // 2
    int32   HeadEffect;  // 3
    int32   ChestEffect;  // 4
    int32   BaseEffect;  // 5
    int32   LeftHandEffect;  // 6
    int32   RightHandEffect;  // 7
    int32   BreathEffect;  // 8
    int32   SpecialEffect[3];  // 9-11
    int32   WorldEffect;  // 12
    int32   SoundID;  // 13
    int32   ShakeID;  // 14
    int32   CharProc[4];  // 15-18
    float   CharParamZero[4];  // 19-22
    float   CharParamOne[4];  // 23-26
    float   CharParamTwo[4];  // 27-30
    float   CharParamThree[4];  // 31-34
};

// SpellVisualPrecastTransitions — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct SpellVisualPrecastTransitionsEntry
{
    int32   ID;  // 0
    char*   PrecastLoadAnimName;  // 1
    char*   PrecastHoldAnimName;  // 2
};

// Startup_Strings — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct Startup_StringsEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name;  // 1
    char*   Message_lang[8];  // 2-9
// uint32  Message_lang_flags;  // 10
};

// Stationery — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct StationeryEntry
{
    uint32  ID;  // [dbd-only] 0
    uint32  ItemID;  // [dbd-only] 1
    char*   Texture;  // 2
    uint32  Flags;  // 3
};

// StringLookups — 2 cols, record_size 8, build 1.12.1.5875. INERT reference (not loaded).
struct StringLookupsEntry
{
    uint32  ID;  // 0
    char*   String;  // 1
};

// TerrainType — 6 cols, record_size 24, build 1.12.1.5875. INERT reference (not loaded).
struct TerrainTypeEntry
{
    uint32  TerrainID;  // 0
    char*   TerrainDesc;  // 1
    int32   FootstepSprayRun;  // 2
    int32   FootstepSprayWalk;  // 3
    uint32  SoundID;  // 4
    uint32  Flags;  // 5
};

// TerrainTypeSounds — 1 cols, record_size 4, build 1.12.1.5875. INERT reference (not loaded).
struct TerrainTypeSoundsEntry
{
    uint32  ID;  // 0
};

// TransportAnimation — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct TransportAnimationEntry
{
    uint32  ID;  // 0
    uint32  TransportID;  // 1
    uint32  TimeIndex;  // 2
    float   PosX;  // 3
    float   PosY;  // 4
    float   PosZ;  // 5
    uint32  SequenceID;  // 6
};

// UISoundLookups — 3 cols, record_size 12, build 1.12.1.5875. INERT reference (not loaded).
struct UISoundLookupsEntry
{
    uint32  ID;  // 0
    uint32  SoundID;  // 1
    char*   SoundName;  // 2
};

// UnitBlood — 10 cols, record_size 40, build 1.12.1.5875. INERT reference (not loaded).
struct UnitBloodEntry
{
    uint32  ID;  // 0
    uint32  CombatBloodSpurtFront[2];  // [dbd-only] 1-2
    uint32  CombatBloodSpurtBack[2];  // [dbd-only] 3-4
    char*   GroundBlood[5];  // 5-9
};

// UnitBloodLevels — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct UnitBloodLevelsEntry
{
    uint32  ID;  // 0
    uint32  Violencelevel_1;  // 1
    uint32  Violencelevel_2;  // 2
    uint32  Violencelevel_3;  // 3
};

// VideoHardware — 22 cols, record_size 88, build 1.12.1.5875. INERT reference (not loaded).
struct VideoHardwareEntry
{
    uint32  ID;  // 0
    uint32  VendorID;  // 1
    uint32  DeviceID;  // 2
    uint32  FarclipIdx;  // 3
    uint32  TerrainLODDistIdx;  // 4
    int32   TerrainShadowLOD;  // 5
    uint32  DetailDoodadDensityIdx;  // 6
    int32   DetailDoodadAlpha;  // 7
    uint32  AnimatingDoodadIdx;  // 8
    int32   Trilinear;  // 9
    int32   NumLights;  // 10
    int32   Specularity;  // 11
    uint32  WaterLODIdx;  // 12
    uint32  ParticleDensityIdx;  // 13
    uint32  UnitDrawDistIdx;  // 14
    uint32  SmallCullDistIdx;  // 15
    uint32  ResolutionIdx;  // 16
    int32   BaseMipLevel;  // 17
    char*   OglOverrides;  // 18
    char*   D3dOverrides;  // 19
    int32   FixLag;  // 20
    int32   Multisample;  // 21
};

// VocalUISounds — 7 cols, record_size 28, build 1.12.1.5875. INERT reference (not loaded).
struct VocalUISoundsEntry
{
    uint32  ID;  // 0
    uint32  VocalUIEnum;  // 1
    uint32  RaceID;  // 2
    uint32  NormalSoundID[2];  // 3-4
    uint32  PissedSoundID[2];  // 5-6
};

// WeaponImpactSounds — 23 cols, record_size 92, build 1.12.1.5875. INERT reference (not loaded).
struct WeaponImpactSoundsEntry
{
    uint32  ID;  // 0
    uint32  WeaponSubClassID;  // 1
    uint32  ParrySoundType;  // 2
    uint32  ImpactSoundID[10];  // 3-12
    uint32  CritImpactSoundID[10];  // 13-22
};

// WeaponSwingSounds2 — 4 cols, record_size 16, build 1.12.1.5875. INERT reference (not loaded).
struct WeaponSwingSounds2Entry
{
    uint32  ID;  // 0
    int32   SwingType;  // 1
    int32   Crit;  // 2
    uint32  SoundID;  // 3
};

// WorldMapContinent — 13 cols, record_size 52, build 1.12.1.5875. INERT reference (not loaded).
struct WorldMapContinentEntry
{
    uint32  ID;  // 0
    uint32  MapID;  // 1
    int32   LeftBoundary;  // 2
    int32   RightBoundary;  // 3
    int32   TopBoundary;  // 4
    int32   BottomBoundary;  // 5
    float   ContinentOffset[2];  // 6-7
    float   Scale;  // 8
    float   TaxiMin[2];  // 9-10
    float   TaxiMax[2];  // 11-12
};

// WorldMapOverlay — 17 cols, record_size 68, build 1.12.1.5875. INERT reference (not loaded).
struct WorldMapOverlayEntry
{
    uint32  ID;  // 0
    int32   MapAreaID;  // 1
    int32   AreaID[4];  // 2-5
    int32   MapPointX;  // 6
    int32   MapPointY;  // 7
    char*   TextureName;  // 8
    int32   TextureWidth;  // 9
    int32   TextureHeight;  // 10
    int32   OffsetX;  // 11
    int32   OffsetY;  // 12
    int32   HitRectTop;  // 13
    int32   HitRectLeft;  // 14
    int32   HitRectBottom;  // 15
    int32   HitRectRight;  // 16
};

// WorldStateUI — 39 cols, record_size 156, build 1.12.1.5875. INERT reference (not loaded).
struct WorldStateUIEntry
{
    uint32  ID;  // 0
    int32   MapID;  // 1
    int32   AreaID;  // 2
    char*   Icon;  // 3
    char*   String_lang[8];  // 4-11
// uint32  String_lang_flags;  // 12
    char*   Tooltip_lang[8];  // 13-20
// uint32  Tooltip_lang_flags;  // 21
    int32   FactionID;  // 22
    int32   StateVariable;  // 23
    int32   Type;  // 24
    char*   DynamicIcon;  // 25
    char*   DynamicTooltip_lang[8];  // 26-33
// uint32  DynamicTooltip_lang_flags;  // 34
    char*   ExtendedUI;  // 35
    int32   ExtendedUIStateVariable[3];  // 36-38
};

// WowError_Strings — 11 cols, record_size 44, build 1.12.1.5875. INERT reference (not loaded).
struct WowError_StringsEntry
{
    int32   ID;  // 0
    int32   Name;  // 1
    char*   Description_lang[8];  // 2-9
// uint32  Description_lang_flags;  // 10
};

// ZoneIntroMusicTable — 5 cols, record_size 20, build 1.12.1.5875. INERT reference (not loaded).
struct ZoneIntroMusicTableEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  SoundID;  // 2
    int32   Priority;  // 3
    int32   MinDelayMinutes;  // 4
};

// ZoneMusic — 8 cols, record_size 32, build 1.12.1.5875. INERT reference (not loaded).
struct ZoneMusicEntry
{
    uint32  ID;  // 0
    char*   SetName;  // 1
    int32   SilenceIntervalMin[2];  // 2-3
    int32   SilenceIntervalMax[2];  // 4-5
    uint32  Sounds[2];  // 6-7
};

#endif
