# Mirrors the option() block and help text in the root CMakeLists.txt.
# Keep these in the same order when adding/removing options.

message("===================================================")
message("Mangos revision       : ${rev_hash} ${rev_date} (${rev_branch} branch)")
message("Build type            : ${CMAKE_BUILD_TYPE}")
message("Install server(s) to  : ${BIN_DIR}")
message("Install configs to    : ${CONF_INSTALL_DIR}")

message("")
message("Detailed Information")
message("+-- operating system  : ${CMAKE_HOST_SYSTEM}")
message("+-- cmake version     : ${CMAKE_VERSION}")
message("")

# Resolved network backend (WITH_IO_URING may be ON but not granted without liburing).
if(WIN32)
    message("Network backend       : IOCP")
elseif(MANGOS_USE_IO_URING)
    message("Network backend       : io_uring")
elseif(APPLE OR CMAKE_SYSTEM_NAME MATCHES "BSD")
    message("Network backend       : kqueue reactor")
else()
    message("Network backend       : epoll reactor")
endif()
message("")

message("Options (root CMakeLists.txt)")
message("---------------------------------------------------")

# --- same order as option() in root CMakeLists.txt ---

# BUILD_MANGOSD (default ON)
if(BUILD_MANGOSD)
    message("BUILD_MANGOSD         : Yes (default)")
else()
    message("BUILD_MANGOSD         : No")
endif()

# BUILD_REALMD (default ON)
if(BUILD_REALMD)
    message("BUILD_REALMD          : Yes (default)")
else()
    message("BUILD_REALMD          : No")
endif()

# BUILD_TOOLS (default ON)
if(BUILD_TOOLS)
    message("BUILD_TOOLS           : Yes (default)")
else()
    message("BUILD_TOOLS           : No")
endif()

# BUILD_CONFEDITOR (default ON, Windows only)
if(BUILD_CONFEDITOR)
    if(WIN32)
        message("BUILD_CONFEDITOR      : Yes (Win32, default)")
    else()
        message("BUILD_CONFEDITOR      : Yes (skipped — Windows only)")
    endif()
else()
    message("BUILD_CONFEDITOR      : No")
endif()

# BUILD_CONFEDITOR_WEB (default ON, Windows + WebView2 SDK)
if(BUILD_CONFEDITOR_WEB)
    if(WIN32)
        if(TARGET mangos-conf-editor-web)
            message("BUILD_CONFEDITOR_WEB  : Yes (WebView2, default)")
        else()
            message("BUILD_CONFEDITOR_WEB  : Yes (skipped — WebView2 SDK missing)")
        endif()
    else()
        message("BUILD_CONFEDITOR_WEB  : Yes (skipped — Windows only)")
    endif()
else()
    message("BUILD_CONFEDITOR_WEB  : No")
endif()

# BUILD_AH_SERVICE (default ON)
if(BUILD_AH_SERVICE)
    message("BUILD_AH_SERVICE      : Yes (default)")
else()
    message("BUILD_AH_SERVICE      : No")
endif()

# SCRIPT_LIB_ELUNA (default ON)
if(SCRIPT_LIB_ELUNA)
    if(BUILD_MANGOSD)
        message("SCRIPT_LIB_ELUNA      : Yes (default)")
        message("    +-- revision      : ${dep_eluna_rev_hash} ${dep_eluna_rev_date} (${dep_eluna_rev_branch} branch)")
    else()
        message("SCRIPT_LIB_ELUNA      : Yes (default, unused without mangosd)")
    endif()
else()
    message("SCRIPT_LIB_ELUNA      : No")
endif()

# SCRIPT_LIB_SD3 (default ON)
if(SCRIPT_LIB_SD3)
    if(BUILD_MANGOSD)
        message("SCRIPT_LIB_SD3        : Yes (default)")
        message("    +-- revision      : ${dep_sd3_rev_hash} ${dep_sd3_rev_date} (${dep_sd3_rev_branch} branch)")
    else()
        message("SCRIPT_LIB_SD3        : Yes (default, unused without mangosd)")
    endif()
else()
    message("SCRIPT_LIB_SD3        : No")
endif()

# PLAYERBOTS (default OFF)
if(PLAYERBOTS)
    if(BUILD_MANGOSD)
        message("PLAYERBOTS            : Yes")
    else()
        message("PLAYERBOTS            : Yes (unused without mangosd)")
    endif()
else()
    message("PLAYERBOTS            : No (default)")
endif()

# SOAP (default OFF)
if(SOAP)
    message("SOAP                  : Yes")
else()
    message("SOAP                  : No (default)")
endif()

# PCH (default ON)
if(PCH)
    message("PCH                   : Yes (default)")
else()
    message("PCH                   : No")
endif()

# WITH_IO_URING (default OFF)
if(WITH_IO_URING)
    if(MANGOS_USE_IO_URING)
        message("WITH_IO_URING         : Yes (granted)")
    else()
        message("WITH_IO_URING         : Yes (not granted — need Linux + liburing)")
    endif()
else()
    message("WITH_IO_URING         : No (default)")
endif()

# WITH_TESTS (default OFF)
if(WITH_TESTS)
    message("WITH_TESTS            : Yes (target: mangos_tests)")
else()
    message("WITH_TESTS            : No (default)")
endif()

# WITH_NET_TESTS (default OFF)
if(WITH_NET_TESTS)
    message("WITH_NET_TESTS        : Yes (socket tests; slow)")
else()
    message("WITH_NET_TESTS        : No (default)")
endif()

# DEBUG (default OFF)
if(DEBUG)
    message("DEBUG                 : Yes")
else()
    message("DEBUG                 : No (default)")
endif()

# WITHOUT_GIT (default OFF)
if(WITHOUT_GIT)
    message("WITHOUT_GIT           : Yes")
    message("")
    message(" *** WITHOUT_GIT - WARNING!")
    message(" *** Without Git installed, proper support may not be given.")
    message(" *** Some additional information that may be required, is only")
    message(" *** given when Git is enabled. Please install Git for support.")
else()
    message("WITHOUT_GIT           : No (default) — Git revision hash enabled")
endif()

message("")
message("===================================================")
